const byte REG_VM0_W = 0x00;    // video mode 0
const byte REG_VM0_R = 0x80;
const byte REG_VM1_W = 0x01;    // video mode 1
const byte REG_VM1_R = 0x81;
const byte REG_HOS_W = 0x02;    // horizontal offset
const byte REG_HOS_R = 0x82;
const byte REG_VOS_W = 0x03;    // vertical offset
const byte REG_VOS_R = 0x83;
const byte REG_DMM_W = 0x04;    // display memory mode
const byte REG_DMM_R = 0x84;
const byte REG_DMAH_W = 0x05;   // display memory address (bit 8)
const byte REG_DMAH_R = 0x85;
const byte REG_DMAL_W = 0x06;   // display memory address (bits 7:0)
const byte REG_DMAL_R = 0x86;
const byte REG_DMDI_W = 0x07;   // display memory data in
const byte REG_DMDI_R = 0x87;
const byte REG_CMM_W = 0x08;    // character memory mode
const byte REG_CMM_R = 0x88;
const byte REG_CMAH_W = 0x09;   // character memory address (bit 8)
const byte REG_CMAH_R = 0x89;
const byte REG_CMAL_W = 0x0A;   // character memory address (bits 7:0)
const byte REG_CMAL_R = 0x8A;
const byte REG_CMDI_W = 0x0B;   // character memory data in
const byte REG_CMDI_R = 0x8B;
const byte REG_OSDM_W = 0x0C;   // OSD insertion mux
const byte REG_OSDM_R = 0x8C;
const byte REG_RB0_W = 0x10;   // row 0 brightness
const byte REG_RB0_R = 0x90;
const byte REG_RB1_W = 0x11;   // row 1 brightness
const byte REG_RB1_R = 0x91;
const byte REG_RB2_W = 0x12;   // row 2 brightness
const byte REG_RB2_R = 0x92;
const byte REG_RB3_W = 0x13;   // row 3 brightness
const byte REG_RB3_R = 0x93;
const byte REG_RB4_W = 0x14;   // row 4 brightness
const byte REG_RB4_R = 0x94;
const byte REG_RB5_W = 0x15;  // row 5 brightness
const byte REG_RB5_R = 0x95;
const byte REG_RB6_W = 0x16;  // row 6 brightness
const byte REG_RB6_R = 0x96;
const byte REG_RB7_W = 0x17;  // row 7 brightness
const byte REG_RB7_R = 0x97;
const byte REG_RB8_W = 0x18;  // row 8 brightness
const byte REG_RB8_R = 0x98;
const byte REG_RB9_W = 0x19;  // row 9 brightness
const byte REG_RB9_R = 0x99;
const byte REG_RB10_W = 0x1A; // row 10 brightness
const byte REG_RB10_R = 0x9A;
const byte REG_RB11_W = 0x1B; // row 11 brightness
const byte REG_RB11_R = 0x9B;
const byte REG_RB12_W = 0x1C; // row 12 brightness
const byte REG_RB12_R = 0x9C;
const byte REG_RB13_W = 0x1D; // row 13 brightness
const byte REG_RB13_R = 0x9D;
const byte REG_RB14_W = 0x1E; // row 14 brightness
const byte REG_RB14_R = 0x9E;
const byte REG_RB15_W = 0x1F; // row 15 brightness
const byte REG_RB15_R = 0x9F;
const byte REG_OSDBL_W = 0x6C;  // OSD black level
const byte REG_OSDBL_R = 0xEC;
const byte REG_STAT_R = 0xA0; // status
const byte REG_DMDO_R = 0xB0; // display memory data out
const byte REG_CMDO_R = 0xC0; // character memory data out

